### ISSUE TITLE
Feature request, add an auto mode for prefers-color-scheme

### ISSUE THREAD

**Issue by riasvdv** [mattgrayisok/craft-dark-mode#11]
As per this post https://paulmillr.com/posts/using-dark-mode-in-css/ it would be nice to have it change depending on the preference of the user.

**Comment by mattgrayisok** [comment]
Thanks for the suggestion. I'm currently trying to figure out how to nicely integrate this with an additional manual switch in the CP. Also the complication of carrying the user's preference as set in the CP between different login devices vs the presence of this dark mode opt-in.

**Comment by mattgrayisok** [comment]
@Rias500 I decided to add a simple switch to the control panel with local storage persistence in [v1.1.0](https://github.com/mattgrayisok/craft-dark-mode/releases/tag/v1.1.0) rather than try to combine logic for both OS level preference and app level preference.

It's a slight annoyance having to flick the switch when you already have dark mode enabled in MacOS but it only needs doing once and saves on complexity.

Hope that works for your use case 🤞
